apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-service
spec:
  selector: 
      app: {{ .Values.image }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
   

